import { imagePanel, runs } from "../../scripts/ascii-art.ts";

/**
 * A source image resolved into ASCII — Gestalt's `AsciiImage`, rendered at build time.
 *
 * **This is the per-card counterpart to the full-bleed drawing.** The drawing is the project's own
 * mark and has one subject; these have three, one per card, which is what stops the three cards
 * reading as one picture cropped three ways.
 *
 * ## ⛔ WHERE THE THREE SOURCES CAME FROM — THIS IS THE ACCOUNT, AND THE OTHER FILES DEFER TO IT
 *
 * `public/ascii/{recycling,reduction,re-anchoring}.png` are **the project owner's own figures,
 * authored in Gestalt.** Not third-party art, not generated by any script, and nothing in this
 * repository produces them — they are inputs, and replacing the files is the whole substitution;
 * no code changes with them.
 *
 * **It is written once here because three partial accounts is how it went wrong.** This docstring
 * used to quote the reference's own file calling them *"generated placeholders… written by a
 * script"* — a true quotation of somebody else's docstring and a false account of these files.
 * `content.ts` called them "the reference's three greyscale placeholders". `ascii-art.ts` says the
 * site's imagery is generated from the project's own drawing, which is true of the PIPELINE and
 * says nothing about these INPUTS. None of the three was wrong in isolation and a reader who
 * opened two of them concluded the repository was shipping unaccounted third-party art — which it
 * is not. The accounting was not missing; it was distributed, and distributed provenance reads as
 * absent provenance.
 *
 * So: if this ever needs restating, restate it HERE and leave the pointers alone.
 *
 * Async because the decode is: a server component may await, and doing this at build time is what
 * keeps the browser from ever fetching the source.
 */
export async function AsciiImage({
  file,
  cols = 68,
  rows = 34,
  gain = 1,
  alt,
}: {
  file: string;
  cols?: number;
  rows?: number;
  gain?: number;
  /** Describes the subject, not the technique. */
  alt: string;
}) {
  const grid = await imagePanel({ file, cols, rows, gain });
  return (
    <div className="panel" role="img" aria-label={alt}>
      <pre className="panel-art" aria-hidden style={{ ["--cols" as string]: String(cols) }}>
        {grid.map((row, y) => (
          <span key={y} className="panel-row">
            {runs(row).map((r, i) => (
              <span key={i} style={{ color: `var(--g-${r.grey})`, ["--g" as string]: r.grey }}>
                {r.text}
              </span>
            ))}
            {"\n"}
          </span>
        ))}
      </pre>
    </div>
  );
}
