/**
 * `flows.json` is the one file in this tool that holds something the user MADE.
 *
 * Everything else — state.json, history.jsonl — is a record of what the tool did and can be
 * regenerated by doing it again. A saved flow cannot. So the property under test is not
 * "saving works"; it is **an unreadable flows file is never written over**.
 *
 * The bug these reproduce: `listFlows()` returned `{ available: true, flows: [] }` for both
 * "no flows yet" and "could not read your flows", and `saveFlow` wrote back what it got. One
 * keypress turned a corrupt file holding twelve flows into a good file holding one, with no
 * message and exit 0. Truncated JSON is not hypothetical — the write is a single
 * `writeFile`, so any process killed mid-write produces it.
 *
 * Each corruption case asserts the bytes on disk are UNCHANGED after the refusal. A refusal
 * that still rewrote the file would pass a test that only checked `ok === false`.
 */

import { mkdtempSync, writeFileSync, readFileSync, existsSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

const HOME = mkdtempSync(join(tmpdir(), "hydra-flows-"));
process.env.HYDRA_HOME = HOME;
const FILE = join(HOME, "flows.json");

const { listFlows, saveFlow, forgetFlow } = await import("../src/flows.mjs");

let failed = 0;
const check = async (name, fn) => {
  try {
    const detail = await fn();
    console.log(`PASS  ${name}${detail ? `  — ${detail}` : ""}`);
  } catch (e) {
    console.log(`FAIL  ${name}  — ${e.message}`);
    failed++;
  }
};

const eq = (a, b, what) => {
  if (a !== b) throw new Error(`${what}: expected ${JSON.stringify(b)}, got ${JSON.stringify(a)}`);
};

const flow = (name) => ({ name, type: "transfer", from: "alice", to: "bob", token: "STRK", amount: "1" });
const reset = () => { if (existsSync(FILE)) rmSync(FILE); };

await check("absent file is 'none yet', not a failure", async () => {
  reset();
  const r = await listFlows();
  eq(r.available, true, "available");
  eq(r.flows.length, 0, "flows");
  return "available: true, flows: []";
});

await check("a flow saves and reads back", async () => {
  reset();
  const s = await saveFlow(flow("first"));
  eq(s.ok, true, "ok");
  const r = await listFlows();
  eq(r.available, true, "available");
  eq(r.flows.length, 1, "flows");
  eq(r.flows[0].name, "first", "name");
});

// The core case. A file truncated mid-write parses to nothing, and used to read as "no flows".
await check("truncated JSON is unavailable, and saving over it is REFUSED", async () => {
  const good = JSON.stringify({ version: 1, flows: [flow("keep-me"), flow("and-me")] }, null, 2);
  writeFileSync(FILE, good.slice(0, Math.floor(good.length / 2)));
  const before = readFileSync(FILE, "utf8");

  const r = await listFlows();
  eq(r.available, false, "available");
  if (!r.error) throw new Error("unavailable with no reason given");

  const s = await saveFlow(flow("new-one"));
  eq(s.ok, false, "save refused");
  if (!s.error.includes(FILE)) throw new Error(`refusal names no file: ${s.error}`);

  // The whole point: the refusal did not write.
  eq(readFileSync(FILE, "utf8"), before, "file on disk");
  return s.error.slice(0, 60) + "…";
});

await check("valid JSON of the wrong shape is unavailable too", async () => {
  writeFileSync(FILE, JSON.stringify({ version: 1 }));
  const before = readFileSync(FILE, "utf8");
  const r = await listFlows();
  eq(r.available, false, "available");
  const s = await saveFlow(flow("new-one"));
  eq(s.ok, false, "save refused");
  eq(readFileSync(FILE, "utf8"), before, "file on disk");
});

await check("forgetFlow blames the file, not the id", async () => {
  writeFileSync(FILE, "{ not json");
  const before = readFileSync(FILE, "utf8");
  const r = await forgetFlow("fkeep-me");
  eq(r.ok, false, "ok");
  if (r.error === "no such flow") throw new Error("blamed the id for an unreadable file");
  if (!r.error.includes(FILE)) throw new Error(`refusal names no file: ${r.error}`);
  eq(readFileSync(FILE, "utf8"), before, "file on disk");
});

await check("a readable file still saves and still forgets", async () => {
  reset();
  await saveFlow(flow("one"));
  await saveFlow(flow("two"));
  eq((await listFlows()).flows.length, 2, "after two saves");
  const f = await forgetFlow("fone");
  eq(f.ok, true, "forget ok");
  eq((await listFlows()).flows.length, 1, "after forget");
});

rmSync(HOME, { recursive: true, force: true });
console.log(failed ? `\n${failed} failed` : "\nall flow-file checks passed");
process.exit(failed ? 1 : 0);
