/**
 * The hydra mark, and the geometry the splash animates over.
 *
 * The art is embedded rather than read from `ascii-art.md` at runtime: that file
 * lives at the repo root, is untracked, and a TUI that renders nothing on a fresh
 * clone because a decorative file is missing is a worse trade than 50 lines here.
 *
 * `rings()` is the whole animation model. Every glyph gets a normalised distance
 * from the centre (0 at the middle, 1 at the furthest corner), measured in
 * DISPLAY space — terminal cells are about twice as tall as they are wide, so a
 * column step counts half a row step. Without that correction the "expanding
 * circle" is a visibly squashed ellipse.
 */

const ART = `
                                          ................
                                   ..............................
                              ........................................
                          ................................................
                       ......................................................
                     ....................                 .....................
                   ................                             .................
                 ..............            ..............            ..............
               .............            ....................            .............
             .............            .......................             ............
            ...:........             .........................              ............
           ...........               ..........................               ...........
          ..........                 ..........................                 ..........
        ..........    ....           ..........................          .....   ..........
        .. ...... .............      ..........................       ............:.........
       .. .......................    ..........................    ..........................
      .............        ......     ........................     ......        .............
     .............          .......   ...    ..........   ....   .......          ...:..... ..
     .. ..... ....           ......   ...      .......     ...   ......           .............
    ..............           ....... .......................... ......            .............
    .. ..... ........    ..   ......  ...........  ...........  ......   ..     ....... ..... ..
    ........ .............    ......  ........................  ......    ............. ..... ..
   .. .....   ..........       ........... .............. ...........       .........   .........
   .. .....       .........      ..................................     ........         ........
   .. .....   .....................:.......  ..........  .............................   ..... ..
   .. .....   .........................   ....... :.......   .........................   ..... ..
   .. .....  .................................... .....................................  ..... ..
   .. .....  ........          .......................................          .......  ..... ..
   .. .....  ......                ........   ........   ........                ......  ..... ..
   ........  .....            ..         ..................         ..            .....  ........
    ........ ....             ...    ..........................    ...            ..... ........
    .. ..... ....              .. ...............  ............... ..              .... ..... ..
    ......... ....            .................      ............. ...           ..... .........
     .. ..... .....         ............                     ...... .. .         ..... ..... ..
     ......... ....... ........ .....        .        .        ..... .... ... ....... ........
      ......... ...................          ...    ...          ................... .........
       .. ...... .................            ........           .................. .........
        .. ...... ........... ....            .......             .... ........... .........
        ...:......  .......  .....             ......            ......  ....... ..........
          ..........         ......           ........           ......         ..........
           ..........        ........       . ........ .       .......        ...........
            ...:.......        ........... ...... ....... ...........        ...........
             ............        ................  ................        ...........
               .............       .............    .............       .............
                 ..............      .........       ..........      ..............
                   ...............                                ..........:....
                     ..................                     ...................
                       ......................................................
                          ................................................
                              ................................:.......
                                  ................................
                                         ..................
`;

/** Rows and columns of the source art, trimmed of the leading newline. */
const GRID = ART.replace(/^\n/, "").replace(/\n$/, "").split("\n");
export const ART_ROWS = GRID.length;
export const ART_COLS = Math.max(...GRID.map((l) => l.length));

/**
 * Sample the art down to fit `cols` x `rows`.
 *
 * Nearest-neighbour, because the source is already a dot-stipple — averaging
 * would turn it grey and lose the outline. Never scales UP: past 1:1 the mark
 * just sits centred, which is what a 200-column terminal should show.
 */
export function scaled(cols, rows) {
  const stepX = Math.max(1, Math.ceil(ART_COLS / Math.max(1, cols)));
  const stepY = Math.max(1, Math.ceil(ART_ROWS / Math.max(1, rows)));
  const out = [];
  for (let y = 0; y < ART_ROWS; y += stepY) {
    const line = GRID[y] ?? "";
    let row = "";
    for (let x = 0; x < ART_COLS; x += stepX) row += line[x] ?? " ";
    out.push(row.replace(/\s+$/, ""));
  }
  return out;
}

/**
 * Glyph cells with a normalised radius, ready to colour by threshold.
 *
 * Returns one entry per NON-BLANK cell only; blanks are never emitted, so a
 * caller can rebuild each line by index without carrying the whitespace through
 * the colour logic.
 */
export function rings(lines) {
  const rows = lines.length;
  const cols = Math.max(1, ...lines.map((l) => l.length));
  const cy = (rows - 1) / 2;
  const cx = (cols - 1) / 2;
  // Halve the horizontal component: a terminal cell is ~2x taller than wide.
  const norm = Math.hypot(cx / 2, cy) || 1;
  const cells = [];
  for (let y = 0; y < rows; y++) {
    for (let x = 0; x < (lines[y]?.length ?? 0); x++) {
      const ch = lines[y][x];
      if (ch === " ") continue;
      cells.push({ x, y, ch, r: Math.hypot((x - cx) / 2, y - cy) / norm });
    }
  }
  return { cells, rows, cols };
}
